### ISSUE TITLE
The exe cant find the spicetify thing.

### ISSUE THREAD

**Issue by Cagecellag** [prochy-exe/controlify#2]
![image](https://github.com/prochy-exe/controlify/assets/143967084/52c7615e-8d69-440b-9da3-9b0154edca7c)

**Comment by prochy-exe** [comment]
Have you installed the spicetify client and the plugin inside of it? Stock Spotify app will not work

**Comment by Cagecellag** [comment]
yea i did install the js file and have spicetify installed

**Comment by prochy-exe** [comment]
Have you enabled controlify in Spotify settings? It's disabled by default. I tried both the server and the plugin on Windows and Linux and it's working fine here

**Comment by Cagecellag** [comment]
oh wow its worked, thanks
